// Данные регионов для карты
const regionsData = [
    {
        id: 'kanto',
        name: 'Kanto',
        title: 'Канто',
        subtitle: 'Первый регион',
        status: 'available',
        icon: 'fas fa-mountain',
        color: '#4ecdc4',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Классический регион, где всё начиналось. Дом для первых покемонов и тренеров.',
        coordinates: { x: 550, y: 250 },
        shape: 'polygon',
        points: [[550,250], [600,230], [620,240], [630,270], [610,290], [590,300], [570,290], [550,270]]
    },
    {
        id: 'johto',
        name: 'Johto',
        title: 'Джото',
        subtitle: 'Традиционный регион',
        status: 'soon',
        icon: 'fas fa-torii-gate',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Регион с богатой историей и традициями. Связан с Канто через горы.',
        coordinates: { x: 450, y: 200 },
        shape: 'circle',
        radius: 35
    },
    {
        id: 'hoenn',
        name: 'Hoenn',
        title: 'Хоэнн',
        subtitle: 'Океанский регион',
        status: 'soon',
        icon: 'fas fa-water',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Регион с обширными океанами и вулканами. Дом для Team Magma и Team Aqua.',
        coordinates: { x: 300, y: 150 },
        shape: 'polygon',
        points: [[300,150], [350,130], [380,140], [390,170], [360,190], [330,180], [310,160]]
    },
    {
        id: 'sinnoh',
        name: 'Sinnoh',
        title: 'Синно',
        subtitle: 'Мифический регион',
        status: 'soon',
        icon: 'fas fa-snowflake',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Холодный регион с глубокой мифологией. Место рождения покемонов.',
        coordinates: { x: 200, y: 100 },
        shape: 'circle',
        radius: 30
    },
    {
        id: 'unova',
        name: 'Unova',
        title: 'Юнова',
        subtitle: 'Урбанистический регион',
        status: 'soon',
        icon: 'fas fa-city',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Современный регион, вдохновлённый Нью-Йорком. Много городских локаций.',
        coordinates: { x: 150, y: 300 },
        shape: 'rect',
        width: 60,
        height: 40
    },
    {
        id: 'kalos',
        name: 'Kalos',
        title: 'Калос',
        subtitle: 'Романтический регион',
        status: 'soon',
        icon: 'fas fa-chess-queen',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Регион, вдохновлённый Францией. Введена мега-эволюция.',
        coordinates: { x: 100, y: 200 },
        shape: 'polygon',
        points: [[100,200], [150,180], [180,210], [150,240], [100,220]]
    },
    {
        id: 'alola',
        name: 'Alola',
        title: 'Алола',
        subtitle: 'Тропический регион',
        status: 'soon',
        icon: 'fas fa-umbrella-beach',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Тропические острова с альтернативными формами покемонов.',
        coordinates: { x: 700, y: 350 },
        shape: 'circle',
        radius: 25
    },
    {
        id: 'galar',
        name: 'Galar',
        title: 'Галар',
        subtitle: 'Индустриальный регион',
        status: 'soon',
        icon: 'fas fa-industry',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Регион, вдохновлённый Великобританией. Введена динамичная битва.',
        coordinates: { x: 50, y: 100 },
        shape: 'rect',
        width: 50,
        height: 30
    },
    {
        id: 'paldea',
        name: 'Paldea',
        title: 'Палдея',
        subtitle: 'Открытый мир',
        status: 'soon',
        icon: 'fas fa-globe-americas',
        color: '#ff6b6b',
        pokemonCount: 0,
        locationCount: 0,
        description: 'Обширный открытый мир с тремя разными историями.',
        coordinates: { x: 50, y: 400 },
        shape: 'polygon',
        points: [[50,400], [100,380], [130,410], [100,440], [50,420]]
    }
];

// Экспортируем данные
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { regionsData };
}